### PR TITLE
Add "request.route" for Django middleware.

### PR DESCRIPTION
**Pull request by sjoerdjob**

### CODE REVIEW

**Comment by maplebed** [comment]
✨

**Comment by MikeGoldsmith** [comment]
Hey @sjoerdjob  - thanks for the PR!

Would you be able to add a test [here](https://github.com/honeycombio/beeline-python/blob/main/beeline/middleware/django/test_django.py) to verify it's working as expected? It helps both verify current functionality, and also safe-guard against it accidentally being changed in the future.

**Comment by sjoerdjob** [comment]
I've added a test-case that verifies it's working as expected. Please check. Unfortunately, what I'm really missing in the test-suite (and I browsed a bit around for examples) is something that would allow me to assert what the shape of the trace is that's send to Honeycomb.

I'd really be happy if it would be possible to express something like:

```
beeline_client = TestClient()
<run code under test>
self.assertEqual(len(beeline_client.traces), 1)
self.assertEqual(beeline_client.traces[0], {
    "...": "...",
    "request.route": "/this/is/the/route/",
    "...": "...",
})
```

Right now the tests only verify that the middleware calls the beeline in a particular way.
For instance,

```
beeline.add_context_field("field1", "value1")
beeline.add_context_field("field2", "value2")
```

and

```
beeline.add_context({
    "field1": "value1",
    "field2": "value2",
})
```

are equivalent in terms of results, but the current test asserts that the variant is used where `add_context_field` is called twice.

**Review by MikeGoldsmith — APPROVED** [review]
The way I've seen this done previously is to provide a custom transmission implementation when creating the beeline. This will allow you to see the events that have been generated and expect to sent to Honeycomb.

There's an example of setting `Mock()` tracer_impl in these [tests](https://github.com/honeycombio/beeline-python/blob/main/beeline/test_beeline.py).

I'm happy with that you've provided here though - thanks for your contribution!

**Comment by MikeGoldsmith** [comment]
Closed and re-opened to trigger CI.

**Review by martin308 — CHANGES_REQUESTED** [review]
@sjoerdjob looks like the linter is a little unhappy. If you can fix that up then we can get this merged!

**Comment by MikeGoldsmith** [comment]
Thanks for working to get this fixed up @sjoerdjob. It looks like the build is failing because the 'watch' step requires a private environment variable that isn't configured to run in forked builds. I'll look into how we want to deal with that going forward but I'm happy to accept this change as it is now.

Thanks!

**Review by MikeGoldsmith — APPROVED** [review]

**Comment by MikeGoldsmith** [comment]
@sjoerdjob we're working on a fix to the workflow that causes PRs to fail CI because of unconfigured env variables. Once it's merged, we can update this change to and we should be good 👍

**Comment by MikeGoldsmith** [comment]
@sjoerdjob we've now removed the component that was failing. Please could you merge main / rebase your changes, and we should be good to merge.

**Review by martin308 — APPROVED** [review]
✅

**Pull request merged**
