### PR TITLE
Add middleware for starlette

### LINKED ISSUE #95: ASGI support
Hi,

I'm using starlette and uvicorn for my python webservice. I've put together a middleware for starlette based on the WSGI one I saw in this codebase.  Worth saying that I have no idea what I'm doing, but I think the code below is what is required.

```
import beeline

from starlette.datastructures import URL, Headers
from starlette.responses import RedirectResponse
from starlette.types import ASGIApp, Receive, Scope, Send


class HoneycombMiddleware:
    def __init__(self, app: ASGIApp) -> None:
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:

        trace = beeline.start_trace(
            context=self.get_context_from_environ(scope))

        def send_wrapper(response):
            beeline.add_context_field(
                "response.status_code", response.get("status"))
            beeline.finish_trace(trace)
            return send(response)

        await self.app(scope, receive, send_wrapper)

    def get_context_from_environ(self, scope):
        request_method = scope.get('method')
        if request_method:
            trace_name = "starlette_http_%s" % request_method.lower()
        else:
            trace_name = "starlette_http"

        headers = Headers(scope=scope)

        return {
            "name": trace_name,
            "type": "http_server",
            "request.host": headers.get('host'),
            "request.method": request_method,
            "request.path": scope.get('path'),
            "request.content_length": int(headers.get('content-length', 0)),
            "request.user_agent": headers.get('user-agent'),
            "request.scheme": scope.get('scheme'),
            "request.query": scope.get('query_string').decode("ascii")
        }
```

### PR DESCRIPTION
**Pull request by jcrist**
This adds a middleware implementation for the Starlette ASGI server.

No tests added for now, wanted to get a 👍 / 👎 on this before spending time figuring out y'alls testing setup.

Fixes #95.

### CODE REVIEW

**Comment by Mause** [comment]
@MikeGoldsmith are you able to review this please?

**Comment by MikeGoldsmith** [comment]
Thanks for the bump @Mause - we'll take a look and provide feedback soon.

**Comment by Mause** [comment]
@MikeGoldsmith ?

**Comment by bdarfler** [comment]
Hi @Mause thank you for the ping. It looks like this slipped through the cracks which I'm very sorry about. Unfortunately, due to holidays and time off, we will have to wait until next week for someone to take a deeper look but I'll make sure that happens.

**Review by MikeGoldsmith — CHANGES_REQUESTED** [review]
Hi @jcrist - I'm sorry for the delay in getting back to you. This fell out of sight, then vacation time, etc.

The PR looks good. Please could you add some rudimentary tests to ensure it's working as expected? You can use the [django](https://github.com/honeycombio/beeline-python/blob/main/beeline/middleware/django/test_django.py) and [flask](https://github.com/honeycombio/beeline-python/blob/main/beeline/middleware/flask/test_flask.py) as a guide.

Thanks!

**Comment by MikeGoldsmith** [comment]
I'm going to accept this PR as is and add follow up tests in #146.

**Review by MikeGoldsmith — APPROVED** [review]

**Pull request merged**
