### PR TITLE
Fix starlette dependencies

### PR DESCRIPTION
**Pull request by MikeGoldsmith**
Note that I upgraded to the latest version of poetry (1.1.4), which caused me to have to update some of the other dependencies. Not sure if it was strictly necessary, but best to be on modern versions of everything. Note that I didn’t fix the tests, though - the tests are definitely broken in both 2.7 and 3.8.3

### CODE REVIEW

**Comment by joshmgrant** [comment]
Hey, I'd like to use the `starlette` middleware. Let me know if you need help getting this merged!

**Comment by robbkidd** [comment]
Rebased against `main`.

**Comment by robbkidd** [comment]
With the starlette effort spread over several PRs, attempting on this one to convince five mini lion bots to come together to form one super-bot.

**Comment by paulosman** [comment]
Closing this. Starlette requires Python 3.6 at a minimum and the Honeycomb beeline still supports Python 2.7 and 3.5. Getting Starlette tests to pass on recent versions as well as older versions of Python is taking a lot of effort. While I understand that this would be great to see for Starlette users, for the time being, we recommend using [opentelemetry-python](https://github.com/open-telemetry/opentelemetry-python) which has [starlette instrumentation](https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-starlette).

**Pull request closed without merging**
