### PR TITLE
Add Starlette tests

### LINKED ISSUE #146: Add tests for Starlette middleware
Add tests for Starlette middleware was added in #109.

### PR DESCRIPTION
**Pull request by MikeGoldsmith**
Adds Starlette as a dependency and adds a test to resolves #146.

### CODE REVIEW

**Comment by MikeGoldsmith** [comment]
I'm struggling adding starlette as a dev dependency for adding a test. I can't seem to add it as a python 3.6+ only dep.

@dsoo any chance you could take a look as you've worked with poetry before?

**Comment by dsoo** [comment]
@MikeGoldsmith - sure, let me take a quick look and see if it's easy.

**Comment by dsoo** [comment]
@MikeGoldsmith - Okay, I puttered around and got the dependencies to work - the tests themselves are still horribly broken, though.

**Comment by dsoo** [comment]
I upgraded to the latest version of poetry (1.1.4), which definitely jiggered things around a bit. Also to note:
```
Python 2.7 will no longer be supported in the next feature release of Poetry (1.2).
You should consider updating your Python version to a supported one.

Note that you will still be able to manage Python 2.7 projects by using the env command.
See https://python-poetry.org/docs/managing-environments/ for more information.
```

**Comment by MikeGoldsmith** [comment]
Closing this PR as we had to remove Starlette integration. We may re-add it in the future, with accompanying tests.

**Pull request closed without merging**
